//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class aml_configuration
    {
        public int config_id { get; set; }
        public string institution_code { get; set; }
        public string institution_name { get; set; }
        public string swift_code { get; set; }
        public string schema_version { get; set; }
        public decimal individual_threshold_amt { get; set; }
        public decimal cooperate_threshold_amt { get; set; }
        public int monitoring_duration { get; set; }
        public Nullable<int> rentity_id { get; set; }
        public string currency_code_local { get; set; }
        public int alert_threshold { get; set; }
        public string transaction_types { get; set; }
        public Nullable<int> risk_score_threshold { get; set; }
        public Nullable<bool> automatic_review { get; set; }
    }
}
