//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class amlAccount
    {
        public string account { get; set; }
        public string account_officer { get; set; }
        public string account_ownership { get; set; }
        public string account_type { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> balance_date { get; set; }
        public string branch { get; set; }
        public string cust_number { get; set; }
        public Nullable<System.DateTime> closed { get; set; }
        public string comments { get; set; }
        public string currency_code { get; set; }
        public string entity_cre_flg { get; set; }
        public string iban { get; set; }
        public string name { get; set; }
        public string new_account { get; set; }
        public Nullable<System.DateTime> opened { get; set; }
        public string previous_status { get; set; }
        public string schm_code { get; set; }
        public string schm_type { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> status_date { get; set; }
        public string swift { get; set; }
        public string temp_account { get; set; }
        public string frez_reason_code { get; set; }
        public Nullable<System.DateTime> acct_cls_date { get; set; }
        public string acct_cls_flg { get; set; }
        public Nullable<decimal> clr_bal_amt { get; set; }
        public Nullable<decimal> cum_cr_amt { get; set; }
        public Nullable<decimal> cum_dr_amt { get; set; }
        public Nullable<decimal> drwng_power { get; set; }
        public string frez_code { get; set; }
        public Nullable<decimal> last_tran_date_cr { get; set; }
        public Nullable<decimal> last_tran_date_dr { get; set; }
        public Nullable<decimal> fx_cum_cr_amt { get; set; }
        public Nullable<decimal> fx_cum_dr_amt { get; set; }
        public Nullable<decimal> sanct_lim { get; set; }
        public Nullable<System.DateTime> last_tran_date { get; set; }
    }
}
