//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class amlphone
    {
        public string phone_id { get; set; }
        public string tph_contact_type { get; set; }
        public string tph_communication_type { get; set; }
        public string tph_country_prefix { get; set; }
        public string tph_extension { get; set; }
        public string tph_number { get; set; }
        public string comments { get; set; }
    }
}
