//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class amlSignatory
    {
        public int id { get; set; }
        public string account { get; set; }
        public string person_id { get; set; }
        public Nullable<bool> primary_sig { get; set; }
        public string role { get; set; }
        public Nullable<System.DateTime> update_date { get; set; }
        public string updated_by { get; set; }
    }
}
