//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class amlTransaction
    {
        public string account_status { get; set; }
        public Nullable<decimal> acctbal { get; set; }
        public Nullable<System.DateTime> acctbaldate { get; set; }
        public Nullable<decimal> amount_local { get; set; }
        public string authipaddress { get; set; }
        public string branchid { get; set; }
        public string chequetxn { get; set; }
        public string chqflag { get; set; }
        public string contracttype { get; set; }
        public Nullable<bool> deleted { get; set; }
        public Nullable<bool> late_deposit { get; set; }
        public string deleted_by { get; set; }
        public Nullable<System.DateTime> deleted_date { get; set; }
        public string drcr_ind { get; set; }
        public Nullable<System.DateTime> entry_time { get; set; }
        public Nullable<decimal> fx_amount { get; set; }
        public string source_branch_id { get; set; }
        public string inp_ip_address { get; set; }
        public string institution_code { get; set; }
        public string institution_name { get; set; }
        public string other_bank_account { get; set; }
        public string other_bank_acct_name { get; set; }
        public string person_type { get; set; }
        public Nullable<bool> posted { get; set; }
        public Nullable<System.DateTime> posted_date { get; set; }
        public string rate { get; set; }
        public string schm_code { get; set; }
        public string schm_type { get; set; }
        public string serial_num { get; set; }
        public string tran_currency { get; set; }
        public Nullable<System.DateTime> tran_date { get; set; }
        public string tran_id { get; set; }
        public string tran_description { get; set; }
        public string tran_subtype { get; set; }
        public string tran_type { get; set; }
        public string txn_country { get; set; }
        public Nullable<System.DateTime> value_date { get; set; }
        public string account { get; set; }
        public string authoriser { get; set; }
        public string customer { get; set; }
        public string inputter_user_id { get; set; }
        public string person_id { get; set; }
    }
}
