//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Currency
    {
        public int CurrencyKey { get; set; }
        public string currency_code { get; set; }
        public string alpha_code { get; set; }
        public string name { get; set; }
        public string category { get; set; }
        public Nullable<int> InsertAuditKey { get; set; }
        public Nullable<int> UpdateAuditKey { get; set; }
    }
}
