//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account_person_role_type> account_person_role_type { get; set; }
        public virtual DbSet<AccountStatusType> AccountStatusTypes { get; set; }
        public virtual DbSet<AccountType> AccountTypes { get; set; }
        public virtual DbSet<CommunicationType> CommunicationTypes { get; set; }
        public virtual DbSet<CompanyInfo> CompanyInfoes { get; set; }
        public virtual DbSet<ConductionType> ConductionTypes { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<entity_person_role_type> entity_person_role_type { get; set; }
        public virtual DbSet<entity_type> entity_type { get; set; }
        public virtual DbSet<EntityLegalFormType> EntityLegalFormTypes { get; set; }
        public virtual DbSet<foreign_currency> foreign_currency { get; set; }
        public virtual DbSet<FundsType> FundsTypes { get; set; }
        public virtual DbSet<GenderType> GenderTypes { get; set; }
        public virtual DbSet<IdentifierType> IdentifierTypes { get; set; }
        public virtual DbSet<indicator_type> indicator_type { get; set; }
        public virtual DbSet<party_role_type> party_role_type { get; set; }
        public virtual DbSet<PersonRelatedPerson> PersonRelatedPersons { get; set; }
        public virtual DbSet<RADAR_FIU_IDENTITY> RADAR_FIU_IDENTITY { get; set; }
        public virtual DbSet<RADAR_IDENTITY_FORMAT> RADAR_IDENTITY_FORMAT { get; set; }
        public virtual DbSet<SubmissionType> SubmissionTypes { get; set; }
        public virtual DbSet<TitleLookup> TitleLookups { get; set; }
        public virtual DbSet<TransactionItemStatu> TransactionItemStatus { get; set; }
        public virtual DbSet<TransactionItemType> TransactionItemTypes { get; set; }
        public virtual DbSet<txn_live1> txn_live1 { get; set; }
        public virtual DbSet<txn_liveOLD> txn_liveOLD { get; set; }
        public virtual DbSet<amlAddress> amlAddresses { get; set; }
        public virtual DbSet<amlbranch> amlbranches { get; set; }
        public virtual DbSet<amlbranchOLD> amlbranchOLDs { get; set; }
        public virtual DbSet<amlDirector> amlDirectors { get; set; }
        public virtual DbSet<amlphone> amlphones { get; set; }
        public virtual DbSet<amlTransaction> amlTransactions { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<PEP> PEPs { get; set; }
        public virtual DbSet<txn_live> txn_live { get; set; }
        public virtual DbSet<amlAccount> amlAccounts { get; set; }
        public virtual DbSet<amlCountry> amlCountries { get; set; }
        public virtual DbSet<amlCustomer> amlCustomers { get; set; }
        public virtual DbSet<amlPerson> amlPersons { get; set; }
        public virtual DbSet<amlTitle> amlTitles { get; set; }
        public virtual DbSet<amlSignatory> amlSignatories { get; set; }
        public virtual DbSet<aml_configuration> aml_configuration { get; set; }
        public virtual DbSet<amlReportingPerson> amlReportingPersons { get; set; }
    }
}
