//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEP
    {
        public string Pep_country { get; set; }
        public string Function_name { get; set; }
        public string Function_description { get; set; }
        public string Pep_date_range { get; set; }
        public string Comments { get; set; }
    }
}
