//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADAR_IDENTITY_FORMAT
    {
        public string ID_FORMAT_SEQUENCE { get; set; }
        public Nullable<decimal> AGE_LIMIT { get; set; }
        public string COUNTRY_CODE { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public Nullable<decimal> DURATION { get; set; }
        public string EXPIRY_BASIS { get; set; }
        public string ID_FORMAT { get; set; }
        public string ISSUER_NAME { get; set; }
        public Nullable<bool> MONITOR_EXPIRY { get; set; }
        public Nullable<decimal> OTHER_DURATION { get; set; }
        public string FIU_IDENTITY { get; set; }
    
        public virtual RADAR_FIU_IDENTITY RADAR_FIU_IDENTITY { get; set; }
    }
}
