//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class RADAR_FIU_IDENTITY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RADAR_FIU_IDENTITY()
        {
            this.RADAR_IDENTITY_FORMAT = new HashSet<RADAR_IDENTITY_FORMAT>();
        }
    
        public string FIU_IDENTITY { get; set; }
        public string CREATED_BY { get; set; }
        public Nullable<System.DateTime> DATE_CREATED { get; set; }
        public string FIU_CODE { get; set; }
        public string FIU_DESCRIPTION { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RADAR_IDENTITY_FORMAT> RADAR_IDENTITY_FORMAT { get; set; }
    }
}
