//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DWBIProjectAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class txn_live1
    {
        public int ID { get; set; }
        public string ACCOUNT_STATUS { get; set; }
        public Nullable<decimal> ACCT_BAL { get; set; }
        public Nullable<System.DateTime> ACCT_BAL_DATE { get; set; }
        public Nullable<decimal> AMOUNT { get; set; }
        public string AUTH_IP_ADDRESS { get; set; }
        public string BRANCH_ID { get; set; }
        public string CHEQUE_TXN { get; set; }
        public decimal DELETED { get; set; }
        public string DELETED_BY { get; set; }
        public Nullable<System.DateTime> DELETED_DATE { get; set; }
        public string DRCR_IND { get; set; }
        public Nullable<System.DateTime> ENTRY_TIME { get; set; }
        public Nullable<decimal> FX_AMOUNT { get; set; }
        public string INIT_BRANCH_ID { get; set; }
        public string INP_IP_ADDRESS { get; set; }
        public string INSTITUTION_CODE { get; set; }
        public string INSTITUTION_NAME { get; set; }
        public string OTHER_BANK_ACCOUNT { get; set; }
        public string OTHER_BANK_ACCT_NAME { get; set; }
        public string PERSON_TYPE { get; set; }
        public decimal POSTED { get; set; }
        public Nullable<System.DateTime> POSTED_DATE { get; set; }
        public decimal RATE { get; set; }
        public string SCHM_CODE { get; set; }
        public string SCHM_TYPE { get; set; }
        public Nullable<decimal> SERIAL_NUM { get; set; }
        public string TRAN_CURRENCY { get; set; }
        public Nullable<System.DateTime> TRAN_DATE { get; set; }
        public string TRAN_ID { get; set; }
        public string TRAN_PARTICULAR { get; set; }
        public string TRAN_SUB_TYPE { get; set; }
        public string TRAN_TYPE { get; set; }
        public Nullable<System.DateTime> VALUE_DATE { get; set; }
        public string ACCOUNT { get; set; }
        public string AUTHORISER { get; set; }
        public string CUSTOMER { get; set; }
        public string INPUTTER_USER_ID { get; set; }
        public string PERSON_ID { get; set; }
        public string TXN_COUNTRY { get; set; }
        public string CONTRACT_TYPE { get; set; }
        public string CONTRACT_NAME { get; set; }
        public Nullable<decimal> CHQ_FLAG { get; set; }
        public Nullable<decimal> ORG_SERIAL { get; set; }
        public string TRAN_COMMENTS { get; set; }
        public string BATCH_TRANS { get; set; }
        public string ADDRESS_OF_BENEFICIARY { get; set; }
        public string PURPOSE_OF_TRANSACTION { get; set; }
        public string KYC_ID { get; set; }
    }
}
